[[redirects]]
  from = "/feed"
  to = "https://blog.moy.cat/atom.xml"
  status = 301
  force = true
[[redirects]]
  from = "/about"
  to = "https://archive.moy.cat/about"
  status = 301
  force = true
[[redirects]]
  from = "/tag/*"
  to = "https://archive.moy.cat/tag/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/category/*"
  to = "https://archive.moy.cat/category/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/author/*"
  to = "https://archive.moy.cat/author/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/2017/*"
  to = "https://archive.moy.cat/2017/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/2018/*"
  to = "https://archive.moy.cat/2018/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/2019/*"
  to = "https://archive.moy.cat/2019/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/2020/*"
  to = "https://archive.moy.cat/2020/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/2021/*"
  to = "https://archive.moy.cat/2021/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404